printWidth: 120
tabWidth: 2
useTabs: true
semi: true
singleQuote: true
trailingComma: 'es5'
bracketSpacing: true
jsxBracketSameLine: false
bracketSameLine: true
arrowParens: avoid
proseWrap: preserve
bracketLine: true
endOfLine: lf
singleAttributePerLine: true
